services:
  firebase-emulators:
    build:
      context: .
      dockerfile: Dockerfile.firebase-emulators
    init: true
    stop_grace_period: 30s
    ports:
      - "4000:4000"
      - "8085:8085"
      - "9099:9099"
      - "9150:9150"
    volumes:
      - ./.firebaserc:/workspace/.firebaserc:ro
      - ./firebase.json:/workspace/firebase.json:ro
      - ./firestore.indexes.json:/workspace/firestore.indexes.json:ro
      - ./firestore.rules:/workspace/firestore.rules:ro
      - ./firebase-state:/workspace/state
